version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=django
    volumes:
      - mariadb:/var/lib/mysql
  
  django:
    image: greglebarbar/django
    build: 
      context: djangoapp
    expose: 
      - "8000"
    depends_on:
      - "mariadb"
    

  nginx:
    image: nginx:1.11
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "django"
    
volumes:
  mariadb:
     #driver: local
     external: true   

